# Basic commands in NumPy

First we will import NumPy module in our notebook.  

In [16]:
import numpy as np #the reason we import is as np is to save time from writing "numpy" everytime we use it

### Let's make an array using NumPy. We will use the command  

In [17]:
a = np.arange(15).reshape(3, 5)

The command arange is used to make array containing equally spaced value. Here 15 in arrange(15) is the value of element we want in our array. Reshape is used to determine the size of our array we will create. 3 is the number of rows and 5 is the number of columns in the array. 

Let us see how our array a looks like: 

In [18]:
a = np.arange(15).reshape(3, 5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


##### Q: Create an array of your name of shape 4x5 using the function given above 

In [20]:
#write your code here 


There is one more way to create an array using numpy

In [25]:
j=np.array([3,2,4,5,8])
#now when you print this 
print(j)

[3 2 4 5 8]


### Next command that we will learn is how to find out dimension of the array. We will use "array_name.ndim". Let's see how it works on our array named a

In [21]:
a.ndim

2

#### Q: Now find out dimension of the array:

In [23]:
p=np.array([3,1,2])

In [26]:
#write your code here



### Next we will learn how to find the shape of our array. We will use "array_name.shape"

In [9]:
a.shape

(3, 5)

Now find the shape of the matrix: 

In [32]:
p=np.array([[3,2,4,5,6],[4,2,6,7,3],[8,10,3,2,5],[0,6,3,4,2]])
print(p)

[[ 3  2  4  5  6]
 [ 4  2  6  7  3]
 [ 8 10  3  2  5]
 [ 0  6  3  4  2]]


In [34]:
#write your code here 


### "array_name.dtype". This command helps to determine the type of data persent in the array. 

In [36]:
a.dtype

dtype('int32')

Now find the data type of the array named "p"

In [ ]:
#write your code here 


Q: Is the code given below correct?

In [ ]:
a = np.array(1,2,3,4)

In [ ]:
#write yes or no below 


### Now we will learn how to create an array with all zeroes

In [41]:
import numpy as np
arr=np.zeros((3,4))
arr               #we write the name of the array that we have created 

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

As you can see, the command creates an array, also known as matrix with 3 rows and 4 columns. 

Q: Write the code to create an array containing all zeroes having 2 rows and 5 columns 

In [ ]:
#write your code here


### Next we will learn how to make an array of all values equal to one 

In [42]:
arr=np.ones( (2,3))
arr

array([[1., 1., 1.],
       [1., 1., 1.]])

Q. Create an array full of ones with 4 rows and 2 colums 

In [ ]:
#write your code here 


### Now we will learn how to perform mathemtical operations on an array

Suppose we have an array [0,1,2] and we want to multiply every element by 2, how do we do it?

In [44]:
a=np.array([0,1,2])
#we simply multiply the array with two 
b=a*2
b

array([0, 2, 4])

Q: Create an array and multiply all its value by 5

In [46]:
#write your code here 





We will learn how to find sqaure of every element in the array

In [47]:
a=np.array([4,6,3,5])
b=a**2
b

array([16, 36,  9, 25], dtype=int32)

Q: Write a program to find the cube of all the elements in the given array

In [ ]:
a=np.array([3,6,9])
#write your code here 



### How to create an array with random numbers

In [14]:
a = np.random.random((2,3))
a

array([[0.43918494, 0.44226312, 0.01551016],
       [0.80159079, 0.88613825, 0.85288834]])

You will get a different result everytime you run this code. So your friend and you will have different results with the same code!

Q: Create an array with random numbers having 4 rows and 3 columns

In [15]:
#write your code here 




We can find sum of all the elements of the array using "array_name.sum()"

In [16]:
a.sum()

3.4375756041460055

We can find minimum and maximum value of the array using the follwoing fuctions:
    

In [17]:
a.min()

0.015510155096980616

In [18]:
a.max()

0.8861382543436812

To find the sum along an axis

In [19]:
a.sum(axis=0)

array([1.24077573, 1.32840138, 0.86839849])

Q: Create your own array and find the sum of all values and minimum and maximum of the values in the array. 

### How to access elements in an array

The numbering in an array starts from 0. So the first element is indexed as 0 and the second one as 1 and so on. 

In array [1,2,3,4,5,6], 1 is at 0th index and 4 is at 3rd index. How do we access these elements? Using the following code:

In [54]:
a=np.array([1,2,3,4,5,6])
a[0]

1

In [55]:
a[3]

4

If we have to slice the array from one index to another. Suppose in the above array, we only want [3,4] and not other values, we slice the array:

In [57]:
a[2:4]

array([3, 4])

3 is at index 2 and 4 is index 3 but we have to add 1 to the upper limit as computer excludes the upper limit. So we will write a [2:(3+1)]

Q: In the below array, slice the array and print only [4,6,2,5]

In [58]:
b=np.array([3,4,6,2,5,6,7,8])
#write your code here 




We can also slice an array by including every second element. Suppose we need [3,6,5,7] in the array b

In [59]:
b[0:7:2]

array([3, 6, 5, 7])

Notice that we have introduced a third element "2" to specify that we need every second element. 

### How to reverse an array

We will make use of slicing here with using ""-1" as our increment instead of 2 in the above example

In [63]:
b[::-1]

array([8, 7, 6, 5, 2, 6, 4, 3])

Our array has been reversed!

Q: Reverse the following array:

In [ ]:
c=np.array([2,4,67,45,98,28,36,38])
#write your code here 




To create arrays with imaginary numbers 

In [3]:
import numpy as np
d=np.array([[1,2,3],[2,4,6]], dtype=complex)
d

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [2.+0.j, 4.+0.j, 6.+0.j]])

In [5]:
c = np.arange(24).reshape(2,3,4)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

To create arrays with linesapces 

In [10]:
a=np.linspace(0,6,1)
a

array([0.])

In [23]:
arr=np.array([1,2,3])
arr*2

array([2, 4, 6])

To print every element in the array, we can use flat attribute

In [25]:
c = np.arange(24).reshape(2,3,4)
for element in c.flat:
    print (element)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


To reshape an array. The shape of an array can be changed with various commands. Note that the following three commands all return a modified array, but do not change the original array:

In [32]:
c.reshape(2,6,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])

To find transpose of an array

In [33]:
c = np.arange(24).reshape(2,3,4)
c.T

array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])

NOTE: The reshape function returns its argument with a modified shape, whereas the ndarray.resize method modifies the array itself

In [34]:
c.reshape(2,6,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])

In [35]:
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [37]:
c.resize(6,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [38]:
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

Creating an identity matrix/array

In [40]:
u = np.eye(2)
u

array([[1., 0.],
       [0., 1.]])

In [41]:
a = np.array([[1.0, 2.0], [3.0, 4.0]])
np.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])